language: php

sudo: true

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.npm

php:
    # We only run the highest and lowest supported versions to reduce the load on travis-ci.org.
    - 7.1
    - 5.6

matrix:
 fast_finish: true
 exclude:
    # MySQL - we do not use the database to store data
    - env: DB=mysqli   PHPUNIT=true    INSTALL=false   CITEST=false
      php: 5.6
    - env: DB=mysqli   PHPUNIT=true    INSTALL=false   CITEST=false
      php: 7.1
 allow_failures:
    - php: 5.6 # travis seems to fail on adding activity - doesn't fail when running behat locally.
    
env:
 global:
  - MOODLE_BRANCH=MOODLE_32_STABLE
 matrix:
  - DB=mysqli
    
before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
