name: Tests

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    env:
      DB: pgsql

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: moodleuser
          POSTGRES_PASSWORD: moodle
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '7.4'
            moodle-branch: 'master'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: this-plugin

      - name: Checkout moodle-plugin-ci
        uses: actions/checkout@v2
        with:
          repository: moodlehq/moodle-plugin-ci
          path: ci

      - name: Composer install
        run: cd ci; composer install

      - name: Set path 1
        run: echo "$(cd ci/bin; pwd)" >> $GITHUB_PATH

      - name: Set path 2
        run: echo "$(cd ci/vendor/bin; pwd)" >> $GITHUB_PATH

      - name: Set AU
        run: sudo locale-gen en_AU.UTF-8

      - name: Install Moodle
        run: moodle-plugin-ci install --branch ${{ matrix.moodle-branch }} --db-user moodleuser --db-pass moodle --plugin this-plugin

      - name: phpunit 
        run: moodle-plugin-ci phpunit --coverage-text --coverage-clover

      - name: coveralls
        env:
          repo_token: ${{ secrets.REPOTOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.REPOTOKEN }}
          COVERALLS_RUN_LOCALLY: 1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-${{ matrix.test_number }}
          parallel: true
          base-path: /home/runner/work/moodle-availability_language/moodle-availability_language/moodle/availability/condition/language
        run: moodle-plugin-ci coveralls-upload
        
  finish:
    needs: cu
    runs-on: ubuntu-latest
    steps:
    - name: coveralls
      env:
        github-token: ${{ secrets.github_token }}
        COVERALLS_REPO_TOKEN: ${{ secrets.REPOTOKEN }}
        COVERALLS_RUN_LOCALLY: 1
        parallel-finished: true
      run: moodle-plugin-ci coveralls-upload
